### ISSUE TITLE
[New Feature] hyprlock support

### ISSUE THREAD

**Issue by ferrreo** [hyprutils/hyprwall#55]
Would be awesome if you could also change the background image of hyprlock

**Comment by nnyyxxxx** [comment]
this can be done with a script, see here:

https://github.com/nnyyxxxx/hyprland/blob/main/scripts/wallpaper.sh
https://github.com/nnyyxxxx/hyprland/blob/main/hypr/hyprlock.conf

**Comment by ferrreo** [comment]
Isn't the whole point of a gui bg image manager so we don't have to script it. You could argue this entire thing could be scripted...

**Comment by nnyyxxxx** [comment]
the gui does everything its supposed to do 

1. be fast
2. set wallpapers
3. view wallpapers
4. search through wallpapers
5. right click enlargement of wallpapers
6. etc

It does not
1. mess with your dot files
2. mess with the applications installed on your system
3. etc
